name: sms4jawaly_flutter
description: A comprehensive Flutter package for integrating SMS services through 4Jawaly API. Supports sending SMS messages, checking balance, and managing sender IDs across multiple platforms.
version: 1.0.6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

homepage: https://github.com/4jawalycom/sms4jawaly-flutter
repository: https://github.com/4jawalycom/sms4jawaly-flutter
issue_tracker: https://github.com/4jawalycom/sms4jawaly-flutter/issues

flutter:
  plugin:
    platforms:
      android:
        package: com.jawaly.sms4jawaly_flutter
        pluginClass: Sms4jawalyFlutterPlugin
      ios:
        pluginClass: Sms4jawalyFlutterPlugin
      web:
        pluginClass: Sms4jawalyFlutterWeb
        fileName: sms4jawaly_flutter_web.dart
      windows:
        pluginClass: Sms4jawalyFlutterWindows
      macos:
        pluginClass: Sms4jawalyFlutterMacOS
      linux:
        pluginClass: Sms4jawalyFlutterLinux
